### ISSUE TITLE
no password validation rules

### ISSUE THREAD

**Issue by sakshiwadekar401** [Swara345565/FitFusion#1]
The current password can be any string, regardless of its strength. It would be beneficial to implement rules for password validation (e.g., minimum length, special characters, uppercase letters) to improve user security.

**Comment by Swara345565** [comment]
This is a great point!Adding password validation rules is crucial for enhancing user security

**Comment by Swara345565** [comment]
Feel Free to Work on the Issue

**Comment by sakshiwadekar401** [comment]
> Feel Free to Work on the Issue

sure!!

**Comment by Swara345565** [comment]
Resolved!!
